CREATE DATABASE QLCB
ON
( 
	NAME = 'QLCBdata',
	FILENAME= 'D:\CSDL\QLCB_data.mdf',
	SIZE =10,
	MAXSIZE = 100,
	FILEGROWTH =5
)
LOG ON
(
	NAME= 'QLCBlog',
	FILENAME = 'D:\CSDL\QLCB_log.ldf',
	SIZE =10,
	MAXSIZE =100,
	FILEGROWTH=5
)

USE QLCB


--TẠO BẢNG

CREATE TABLE KHHANG
(
	MAKH  CHAR (6)  check (MAKH LIKE  ('[A-Z][A-Z][0-9][0-9][0-9][0-9]' )),
	HOTEN NVARCHAR (50),
	NGAYSINH DATE,
	PHAI CHAR(3) CHECK (PHAI='F' OR PHAI='M') default('F'),
	SOCMND INT,
	DIACHI NVARCHAR(100),
	SDTHOAI TEXT UNIQUE,
	PRIMARY KEY(MAKH)
)
CREATE TABLE CHBAY
(
	MACB  CHAR(6) check ((MACB LIKE  '[%N%][%D%][0-9][0-9][0-9][0-9]') or (MACB LIKE  '[%N%][%N%][0-9][0-9][0-9][0-9]'),
	SBDI NVARCHAR(50),
	SBDEN CHAR (3), 
	GIODI TIME,
	GIODEN TIME,
	PRIMARY KEY(MACB)
)

CREATE TABLE DATCHO
(	
	MAKH CHAR (6)  check (MAKH LIKE  ('[A-Z][A-Z][0-9][0-9][0-9][0-9]' )),
	MACB CHAR (6)  check (MAKH LIKE  ('[A-Z][A-Z][0-9][0-9][0-9][0-9]' )),
	NGAYDI DATETIME ,
	STTGHE INT, 
	LOAIVE VARCHAR(15) CHECK (LOAIVE='VE THUONG' OR LOAIVE='THUONG GIA') default('VE THUONG')
	TIENVE INT, 
	PRIMARY KEY (MAKH,MACB,NGAYDI)
)


CREATE TABLE NHANVIEN
( 
	MANV  CHAR(4) check (MANV LIKE  '[0-9][0-9][0-9][0-9]'),
	HOTENNV NVARCHAR(50),
	GIOITINH CHAR (3) check (GIOITINH='nu' or GIOITINH='nam'),
	EMAIL CHAR(30),
	LUONG INT,
	LOAINV VARCHAR(10) check (LOAINV='1' OR LOAINV='0'),
	PRIMARY KEY(MANV)
)
CREATE TABLE PHANCONG
(
	MAKH CHAR (6),
	MACB CHAR (6),
	NGAYDI DATETIME ,
)


--Tao khoa 
ALTER TABLE DATCHO ADD CONSTRAINT FK_DATCHO_KHHANG FOREIGN KEY (MAKH) REFERENCES KHHANG(MAKH)
ALTER TABLE DATCHO  ADD CONSTRAINT FK_DATCHO_CHBAY FOREIGN KEY (MACB) REFERENCES CHBAY(MACB)
ALTER TABLE DATCHO ADD CONSTRAINT FK_DATCHO_PHANCONG FOREIGN KEY (MACB) REFERENCES PHANCONG(MACB)
ALTER TABLE PHANCONG  ADD CONSTRAINT FK_PHANCONG_CHBAY FOREIGN KEY (MACB) REFERENCES CHBAY(MACB)
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE PHANCONG ADD CONSTRAINT FK_PHANCONG_DATCHO FOREIGN KEY (NGAYDI) REFERENCES DATCHO(NGAYDI)



--Xoa khoa ngoai
ALTER TABLE DATCHO DROP CONSTRAINT  FK_DATCHO_KHHANG
ALTER TABLE DATCHO DROP CONSTRAINT  FK_DATCHO_CHBAY
ALTER TABLE DATCHO DROP CONSTRAINT  FK_DATCHO_PHANCONG
ALTER TABLE PHANCONG DROP CONSTRAINT  FK_PHANCONG_CHBAY
ALTER TABLE PHANCONG DROP CONSTRAINT  FK_PHANCONG_NHANVIEN
ALTER TABLE PHANCONG DROP CONSTRAINT FK_PHANCONG_DATCHO


 
--NHẬP DỮ LIỆU
--Khách Hàng
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values
INSERT INTO KHHANG values



--Chuyến Bay
INSERT INTO CHBAY values
INSERT INTO CHBAY values
INSERT INTO CHBAY values
INSERT INTO CHBAY values
INSERT INTO CHBAY values




--Đặt Chỗ
INSERT INTO DATCHO values
INSERT INTO DATCHO values
INSERT INTO DATCHO values
INSERT INTO DATCHO values
INSERT INTO DATCHO values



--Nhân Viên
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values
INSERT INTO NHANVIEN values


--Phân Công
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values
INSERT INTO PHANCONG  values



--CÂU LỆNH UPDATE

UPDATE KHHANG SET 
UPDATE CHBAY SET 
UPDATE DATCHO SET 
UPDATE NHANVIEN SET
UPDATE PHANCONG SET 




--CÂU LỆNH CHẠY BẢNG

SELECT * FROM KHHANG
SELECT * FROM CHBAY
SELECT * FROM DATCHO
SELECT * FROM NHANVIEN
SELECT * FROM PHANCONG


--Tạo user 
 CREATE LOGIN user03 WITH PASSWORD = '333456'
 CREATE USER phu FOR LOGIN user03

 --Xoa tai khoan user
 DROP USER phu
 
 --Cấp toàn quyền cho 1 user
GRANT insert,delete,alter ON NHANVIEN TO phu

--Thu hồi quyền cho 1 user
REVOKE insert, delete, alter ON PHANCONG FROM phu 
